# Generated by Django 4.2 on 2026-03-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=100, unique=True, verbose_name='Chave no PDF')),
                ('target_key', models.CharField(max_length=100, verbose_name='Coluna no BAT')),
            ],
            options={
                'verbose_name': 'Regra de Mapeamento',
                'verbose_name_plural': 'Regras de Mapeamento',
                'ordering': ['source_key'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('produtos', 'Produtos'), ('clientes', 'Clientes'), ('fornecedores', 'Fornecedores'), ('vendas', 'Vendas'), ('generic', 'Genérico')], max_length=50, unique=True, verbose_name='Tipo de Relatório')),
                ('columns', models.TextField(help_text='Lista de colunas separadas por vírgula na ordem correta.', verbose_name='Colunas BAT')),
            ],
            options={
                'verbose_name': 'Esquema de Relatório',
                'verbose_name_plural': 'Esquemas de Relatórios',
            },
        ),
    ]
