# Generated by Django 4.2 on 2026-03-31 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100, verbose_name='Chave de API')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Esquema')),
                ('columns', models.TextField(help_text='Lista de colunas separadas por vírgula na ordem correta.', verbose_name='Colunas BAT')),
            ],
            options={
                'verbose_name': 'Esquema de Relatório',
                'verbose_name_plural': 'Esquemas de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=100, verbose_name='Chave no PDF')),
                ('target_key', models.CharField(max_length=100, verbose_name='Coluna no BAT (Destino)')),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='converter.reportschema', verbose_name='Esquema Vinculado')),
            ],
            options={
                'verbose_name': 'Regra de Mapeamento',
                'verbose_name_plural': 'Regras de Mapeamento',
                'ordering': ['source_key'],
                'unique_together': {('schema', 'source_key')},
            },
        ),
    ]
